version: "3.8"
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    ports:
      - "3306:3306"
    volumes:
      - ~/.docker-conf/db/data/:/var/lib/mysql/
    environment:
      - MYSQL_DATABASE=users
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_ROOT_PASSWORD=mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - extranet

  service:
    build:
      context: .
    ports:
      - '8010:8010'
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 100M
    environment:
      - PORT=8010
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=users
      - DB_USERNAME=mysql
      - DB_PASSWORD=mysql
    depends_on:
      db:
        condition: service_healthy
    networks:
      - extranet
networks:
  extranet:
    name: extranet-network

